#ifndef _H_XSL_INSTRUCTION
#define _H_XSL_INSTRUCTION

#include <vector>
#include "../Xml/Xml.hpp"


namespace Xsl
{

    /**
     * Defines a XSL instruction interface
     */
    class Instruction
    {
    public:

        /**
         * Execution of an instruction Xsl <forEachElement> in the given <context>, in the <xslDoc>
         * @param context the Element context in which we examine to execute the instruction 
         * to itself or some children.
         * @param xslDoc the XSL document that is used for the transformation
         * @param forEachElement the xsl element corresponding to the instruction.
         *
         *@return the result Nodes generated by the instruction 
         */
        virtual
        std::vector <Xml::Node *>
        operator () (
            Xml::Element const * context,
            Xml::Document const & xslDoc,
            Xml::Element const * forEachElement
        ) const = 0;
    };

}

#endif
