#ifndef _H_XML_PARSER
#define _H_XML_PARSER

#define YY_NO_UNPUT

#include <iostream>
#include <stdio.h>
#include <string>


#include "XmlDocument.hpp"
#include "XmlLog.hpp"


/*
 * Includes the header generated by BISON
 */
#include "XmlParser.y.hpp"


int yyerror(char const *s);
int yyerror(std::string const & s);


namespace Xml
{

    /*
     * Parse a XML file
     *
     * @param path is the file path to parse
     * @param log is the output log
     */
    Document *
    load(std::string const & path, Xml::Log * log = nullptr);

    /*
     * Parse a XML from a string
     *
     * @param xmlContent is the xml string to parse
     * @param log is the output log
     */
    Document *
    parse(std::string const & xmlContent, Xml::Log * log = nullptr);

}

#endif //_H_XML_PARSER
